name: StructureCompass
version: ${project.version}
main: me.polishkrowa.structurecompass.StructureCompass
api-version: 1.17
softdepend:
  - Vault

commands:
  structure-compass:
    aliases: [sc, s-c]
    permission: structure-compass.use

permissions:
  structure-compass.use:
    default: op
    description: "Allows usage of the command"